<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_TestSuit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e848cceb-4a66-425c-9179-5c8a76f044dc</testSuiteGuid>
   <testCaseLink>
      <guid>dbd20fbd-0325-4eb4-a461-645a5d209a71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/TestLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0977ecfd-249d-43b2-b3a6-ef452f015c0f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login/LoginData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0977ecfd-249d-43b2-b3a6-ef452f015c0f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b36861fd-b2a5-4b23-b654-a5494b20d633</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0977ecfd-249d-43b2-b3a6-ef452f015c0f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>076f7cc7-b5e2-4255-a8a5-f3864098576d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
